[pytest]
filterwarnings =
    ignore:.*builtin type swigvarlink has no __module__ attribute.*:DeprecationWarning
    ignore:.*builtin type SwigPyPacked has no __module__ attribute.*:DeprecationWarning
    ignore:.*builtin type SwigPyObject has no __module__ attribute.*:DeprecationWarning
    ignore:.*You are using a non-supported Python version.*:FutureWarning
    ignore:.*You are using a Python version 3.9 past its end of life.*:FutureWarning
    ignore:.*google\.generativeai.*:FutureWarning
    ignore:.*The default value of `allowed_objects` will change.*
    ignore:.*The default value of `allowed_objects` will change.*:DeprecationWarning
    ignore:.*Setting per-request cookies=<...> is being deprecated.*:DeprecationWarning
    ignore:.*You should not use the 'timeout' argument with the TestClient.*:DeprecationWarning
