import logging
from typing import TypedDict, List, Dict, Any, Optional
from langgraph.graph import StateGraph, START, END
from langgraph.types import interrupt, Command

from src.agent.tools import rag_search, get_company_data
from src.agent.prompts import DRAFT_SECTION_SYSTEM_PROMPT
from src.agent.groq_client import RateLimitAwareGroqClient

logger = logging.getLogger(__name__)

class AgentState(TypedDict):
    company_name: str
    current_section: str
    
    # Contexts
    regulatory_context: str
    precedent_context: str
    company_facts: str
    
    # Validation
    consistency_errors: List[Dict[str, Any]]
    
    # Drafting
    draft_text: str
    human_feedback: str
    status: str

# Nodes
def regulatory_retrieval_node(state: AgentState) -> dict:
    logger.info(f"Retrieving regulatory context for {state['current_section']}...")
    # For a full implementation, the query would be generated by an LLM planner.
    # Here we use the section name directly for the prototype.
    context = rag_search(
        query=f"What are the ICDR requirements for {state['current_section']}?",
        corpus="regulatory",
        query_type="compliance",
        k=3
    )
    return {"regulatory_context": context}

def precedent_retrieval_node(state: AgentState) -> dict:
    logger.info(f"Retrieving precedent context for {state['current_section']}...")
    context = rag_search(
        query=f"Show me examples of the {state['current_section']} section.",
        corpus="precedent",
        query_type="precedent",
        k=3
    )
    return {"precedent_context": context}

def data_fetch_node(state: AgentState) -> dict:
    logger.info(f"Fetching structured company facts for {state['company_name']}...")
    facts = get_company_data(state["company_name"])
    return {"company_facts": facts}

def consistency_validator_node(state: AgentState) -> dict:
    # A simplified consistency check for the hackathon
    logger.info("Running consistency validations...")
    errors = []
    
    # Simulated check: if generating 'Capital Structure' and we detect negative net worth, flag it.
    if state["current_section"] == "Capital Structure" and "NetWorth=-" in state.get("company_facts", ""):
        errors.append({
            "field": "net_worth_lakhs",
            "fix": "Company has negative net worth. Eligibility may be compromised. Please review."
        })
        
    return {"consistency_errors": errors}

def draft_generation_node(state: AgentState) -> dict:
    logger.info("Drafting section using Groq Llama 3.3 70B...")
    
    client = RateLimitAwareGroqClient()
    
    # Build prompt
    user_prompt = f"""Draft the '{state['current_section']}' section.
    
REGULATORY CONTEXT:
{state.get('regulatory_context', 'None')}

PRECEDENT EXAMPLES:
{state.get('precedent_context', 'None')}

COMPANY FACTS:
{state.get('company_facts', 'None')}
"""

    if state.get("human_feedback"):
        user_prompt += f"\n\nHUMAN REVISION REQUEST:\n{state['human_feedback']}\nPlease rewrite the draft incorporating this feedback."

    messages = [
        {"role": "system", "content": DRAFT_SECTION_SYSTEM_PROMPT},
        {"role": "user", "content": user_prompt}
    ]
    
    draft = client.generate(messages, max_tokens=2500)
    
    return {"draft_text": draft}

def hitl_review_interrupt(state: AgentState):
    logger.info("Interrupting graph for Human-in-the-Loop Review...")
    
    payload = {
        "view": "promoter",
        "company_name": state["company_name"],
        "section_name": state["current_section"],
        "draft_text": state["draft_text"],
        "consistency_errors": state.get("consistency_errors", [])
    }
    
    # LangGraph pauses execution here and returns the payload to the caller
    human_decision = interrupt(payload)
    
    # When resumed via Command(resume=...), human_decision holds the payload sent back.
    # We return it dynamically using Command to route to the correct next node.
    action = human_decision.get("action")
    
    if action == "approve":
        return Command(goto=END, update={"status": "promoter_reviewed", "human_feedback": ""})
    elif action == "revise":
        feedback = human_decision.get("feedback", "Please revise.")
        return Command(goto="draft_generation", update={"human_feedback": feedback})
    else:
        return Command(goto=END, update={"status": "rejected"})

from langgraph.checkpoint.memory import MemorySaver

# Build Graph
def build_orchestrator() -> StateGraph:
    builder = StateGraph(AgentState)
    
    builder.add_node("regulatory_retrieval", regulatory_retrieval_node)
    builder.add_node("precedent_retrieval", precedent_retrieval_node)
    builder.add_node("data_fetch", data_fetch_node)
    builder.add_node("consistency_validator", consistency_validator_node)
    builder.add_node("draft_generation", draft_generation_node)
    builder.add_node("hitl_review", hitl_review_interrupt)
    
    # Control flow
    # 1. Parallel start
    builder.add_edge(START, "regulatory_retrieval")
    builder.add_edge(START, "precedent_retrieval")
    builder.add_edge(START, "data_fetch")
    
    # 2. Wait for all 3 data sources to finish, then validate
    builder.add_edge(["regulatory_retrieval", "precedent_retrieval", "data_fetch"], "consistency_validator")
    
    # 3. Draft
    builder.add_edge("consistency_validator", "draft_generation")
    
    # 4. Review
    builder.add_edge("draft_generation", "hitl_review")
    
    memory = MemorySaver()
    return builder.compile(checkpointer=memory)

# Global Compiled Graph
graph = build_orchestrator()
